public enum SanctuaryAssignmentFailureReason
{
    None,
    ServiceNotInitialized,
    InvalidPlayer,
    NoAuthority,
    OutsideSimulation,
    AssignmentNotFound,
    ProgressReaderUnavailable,
    InvalidProgressSnapshot,
    QuotaIncomplete,
    AssignmentNotRequested,
    PlayerUnavailable,
    NoSanctuariesConfigured,
    NoFreeSanctuary,
    SanctuaryRegistryInconsistent,
    DuplicateExistingAssignment,
    ReservationConflict
}
