/// <summary>Gameplay origin of provisional experience generated by one raid participation.</summary>
public enum ExpeditionExperienceCategory : byte
{
    Kill = 0,
    Assist = 1,
    Exploration = 2,
    ExtractedLoot = 3
}
